# Generated by Django 4.2 on 2023-04-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_alter_case_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='hashid',
            field=models.CharField(max_length=50),
        ),
    ]
