# Generated by Django 4.2 on 2023-04-30 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_remove_case_date_case_ddate_modified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='ddate_modified',
            new_name='date_modified',
        ),
    ]
