# Generated by Django 4.2 on 2023-06-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0005_rename_ddate_modified_case_date_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('rate', models.FloatField()),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
