# Generated by Django 4.2 on 2023-06-26 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0006_rates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rates',
            new_name='Rate',
        ),
    ]
