# Generated by Django 4.2.3 on 2023-10-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0010_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardCompetitiveEasyMode',
            fields=[
                ('playerID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=12)),
                ('streak', models.IntegerField()),
                ('rank', models.CharField(max_length=12)),
                ('score', models.FloatField()),
            ],
        ),
    ]
