# Generated by Django 4.2.3 on 2023-10-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0011_leaderboardcompetitiveeasymode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboardcompetitiveeasymode',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='leaderboardcompetitiveeasymode',
            name='rank',
            field=models.CharField(max_length=22),
        ),
    ]
