# Generated by Django 4.2.3 on 2023-10-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0011_leaderboardcompetitiveeasymode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardSurvivalEasyMode',
            fields=[
                ('playerID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('streak', models.IntegerField()),
                ('rank', models.CharField(max_length=22)),
                ('score', models.FloatField()),
                ('length', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LeaderboardSurvivaleMediumMode',
            fields=[
                ('playerID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('streak', models.IntegerField()),
                ('rank', models.CharField(max_length=22)),
                ('score', models.FloatField()),
                ('length', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LeaderboardSurvivalExpertMode',
            fields=[
                ('playerID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('streak', models.IntegerField()),
                ('rank', models.CharField(max_length=22)),
                ('score', models.FloatField()),
                ('length', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LeaderboardSurvivalHardMode',
            fields=[
                ('playerID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('streak', models.IntegerField()),
                ('rank', models.CharField(max_length=22)),
                ('score', models.FloatField()),
                ('length', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LeaderboardSurvivalOhnepixelMode',
            fields=[
                ('playerID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('streak', models.IntegerField()),
                ('rank', models.CharField(max_length=22)),
                ('score', models.FloatField()),
                ('length', models.CharField(max_length=10)),
            ],
        ),
    ]
