# Generated by Django 4.2.3 on 2023-10-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0012_alter_leaderboardcompetitiveeasymode_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardCompetitiveMediumMode',
            fields=[
                ('playerID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('streak', models.IntegerField()),
                ('rank', models.CharField(max_length=22)),
                ('score', models.FloatField()),
            ],
        ),
    ]
