# Generated by Django 4.2.3 on 2023-10-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0013_leaderboardsurvivalmediummode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboardcompetitiveeasymode',
            name='name',
            field=models.CharField(default='No Name provided', max_length=20),
        ),
    ]
