# Generated by Django 4.2.3 on 2023-10-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0013_leaderboardcompetitivemediummode'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardCompetitiveExpertMode',
            fields=[
                ('playerID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('streak', models.IntegerField()),
                ('rank', models.CharField(max_length=22)),
                ('score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LeaderboardCompetitiveHardMode',
            fields=[
                ('playerID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('streak', models.IntegerField()),
                ('rank', models.CharField(max_length=22)),
                ('score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LeaderboardCompetitiveOhnepixelMode',
            fields=[
                ('playerID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('streak', models.IntegerField()),
                ('rank', models.CharField(max_length=22)),
                ('score', models.FloatField()),
            ],
        ),
    ]
