# Generated by Django 4.2.16 on 2024-10-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0015_alter_leaderboardcompetitiveeasymode_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSLeaderboardEntry',
            fields=[
                ('rsn', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('weeklybosskills', models.IntegerField()),
                ('totalxp', models.FloatField()),
                ('weeklyskillxp', models.FloatField()),
                ('event', models.CharField(max_length=20)),
            ],
        ),
    ]
