# Generated by Django 4.2.16 on 2024-10-06 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0018_rsleaderboardentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RSLeaderboardEntry',
        ),
    ]
