# Generated by Django 4.2.16 on 2024-10-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0020_rsleaderboardentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weeklys',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('skill', models.CharField(max_length=45)),
                ('boss', models.CharField(max_length=45)),
            ],
        ),
    ]
