# Generated by Django 4.2.16 on 2024-10-10 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0021_weeklys'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsleaderboardentry',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
