# Generated by Django 4.2.16 on 2024-10-16 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0022_rsleaderboardentry_date_modified'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Case',
        ),
        migrations.DeleteModel(
            name='LeaderboardCompetitiveEasyMode',
        ),
        migrations.DeleteModel(
            name='LeaderboardCompetitiveExpertMode',
        ),
        migrations.DeleteModel(
            name='LeaderboardCompetitiveHardMode',
        ),
        migrations.DeleteModel(
            name='LeaderboardCompetitiveMediumMode',
        ),
        migrations.DeleteModel(
            name='LeaderboardCompetitiveOhnepixelMode',
        ),
        migrations.DeleteModel(
            name='LeaderboardSurvivalEasyMode',
        ),
        migrations.DeleteModel(
            name='LeaderboardSurvivalExpertMode',
        ),
        migrations.DeleteModel(
            name='LeaderboardSurvivalHardMode',
        ),
        migrations.DeleteModel(
            name='LeaderboardSurvivalMediumMode',
        ),
        migrations.DeleteModel(
            name='LeaderboardSurvivalOhnepixelMode',
        ),
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
