# Generated by Django 4.2.16 on 2025-09-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0023_delete_case_delete_leaderboardcompetitiveeasymode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GainsLeaderboard',
            fields=[
                ('rsn', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('points', models.IntegerField()),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RaidsLeaderboard',
            fields=[
                ('rsn', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('coxkcstart', models.IntegerField()),
                ('coxkccurrent', models.IntegerField()),
                ('toakcstart', models.IntegerField()),
                ('toakccurrent', models.IntegerField()),
                ('tobkcstart', models.IntegerField()),
                ('tobkccurrent', models.IntegerField()),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
